# Generated by Django 3.2.6 on 2021-08-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datapoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=100)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Elevation', models.FloatField()),
                ('Object_Tags', models.CharField(max_length=100)),
                ('Object_Count', models.FloatField()),
                ('Datapoint_Group', models.CharField(max_length=100)),
                ('Image', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'datapoint',
            },
        ),
    ]
